# Generated by Django 2.2.9 on 2020-01-24 14:30

from django.db import migrations, models
import inventory.utils


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to=inventory.utils.uuid_upload_to),
        ),
    ]
